# Generated by Django 4.1.13 on 2023-12-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=500)),
                ('ratings', models.FloatField()),
                ('rating_nb', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('book_url', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('book_id', models.FloatField()),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
