# Generated by Django 4.1.13 on 2023-12-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_url',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rating_nb',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ratings',
        ),
    ]
