# Generated by Django 4.1.13 on 2023-12-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_remove_book_author_remove_book_book_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=500)),
                ('ratings', models.FloatField()),
                ('rating_nb', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('book_url', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('book_id', models.FloatField()),
                ('pages', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
